// Full insurance product catalog for CoverScore Rating Engine
// Each product: { code, name, description, category, input_schema, icon, classes, rates }

const catalog = [
  // ===== A. PERSONAL INSURANCE - Life & Family =====
  { code: 'TERM_LIFE', name: 'Term Life Insurance', desc: 'Life cover for a specified term with premium guaranteed', category: 'LIFE', icon: 'g', inputs: { sumInsured: { label: 'Sum Assured', type: 'number', required: true }, age: { label: 'Age', type: 'number', required: true }, gender: { label: 'Gender', type: 'select', options: ['Male', 'Female'], required: true }, policyTerm: { label: 'Policy Term (Years)', type: 'select', options: [5, 10, 15, 20, 25, 30], required: true } }, classes: ['Standard', 'Preferred', 'Super Preferred'], rates: { Standard: 0.008, Preferred: 0.006, SuperPreferred: 0.004 }, min_premium: 50000 },
  { code: 'WHOLE_LIFE', name: 'Whole Life Insurance', desc: 'Lifetime cover with cash value accumulation', category: 'LIFE', icon: 'g', inputs: { sumInsured: { label: 'Sum Assured', type: 'number', required: true }, age: { label: 'Age', type: 'number', required: true } }, classes: ['Standard', 'Preferred'], rates: { Standard: 0.015, Preferred: 0.012 }, min_premium: 100000 },
  { code: 'ENDOWMENT', name: 'Endowment Assurance', desc: 'Savings plus protection plan with maturity benefit', category: 'LIFE', icon: 'g', inputs: { sumInsured: { label: 'Sum Assured', type: 'number', required: true }, age: { label: 'Age', type: 'number', required: true }, term: { label: 'Term (Years)', type: 'number', required: true } }, classes: ['Standard'], rates: { Standard: 0.025 }, min_premium: 100000 },
  { code: 'EDUCATION', name: 'Education Plan', desc: 'Child education savings plan with guaranteed maturity value', category: 'LIFE', icon: 'g', inputs: { childAge: { label: 'Child Age', type: 'number', required: true }, maturityValue: { label: 'Maturity Value', type: 'number', required: true }, term: { label: 'Term (Years)', type: 'number', required: true } }, classes: ['Standard'], rates: { Standard: 0.02 }, min_premium: 50000 },
  { code: 'FAMILY_INCOME', name: 'Family Income Benefit', desc: 'Regular monthly income to family in the event of death', category: 'LIFE', icon: 'g', inputs: { monthlyBenefit: { label: 'Monthly Benefit', type: 'number', required: true }, term: { label: 'Benefit Term (Years)', type: 'number', required: true } }, classes: ['Standard'], rates: { Standard: 0.005 }, min_premium: 30000 },
  { code: 'MORTGAGE_PROT', name: 'Mortgage Protection', desc: 'Protects the loan balance in case of death or disability', category: 'LIFE', icon: 'g', inputs: { loanBalance: { label: 'Loan Balance', type: 'number', required: true }, loanTerm: { label: 'Loan Term (Years)', type: 'number', required: true } }, classes: ['Standard'], rates: { Standard: 0.003 }, min_premium: 25000 },
  { code: 'FUNERAL', name: 'Funeral Expense Plan', desc: 'Fixed benefit funeral cover with immediate payouts', category: 'LIFE', icon: 'g', inputs: { sumInsured: { label: 'Benefit Amount', type: 'select', options: [100000, 200000, 500000, 1000000], required: true } }, classes: ['Standard'], rates: { Standard: 0.01 }, min_premium: 10000 },
  { code: 'CREDIT_LIFE', name: 'Credit Life Insurance', desc: 'Covers outstanding loan balance on death or disability', category: 'LIFE', icon: 'g', inputs: { loanAmount: { label: 'Loan Amount', type: 'number', required: true }, loanDuration: { label: 'Loan Duration (Months)', type: 'number', required: true } }, classes: ['Standard'], rates: { Standard: 0.002 }, min_premium: 5000 },
  { code: 'KEYMAN_LIFE', name: 'Key Person Life', desc: 'Life cover on key employees whose loss would impact the business', category: 'LIFE', icon: 'g', inputs: { sumInsured: { label: 'Sum Assured', type: 'number', required: true }, occupation: { label: 'Occupation Class', type: 'select', options: ['Professional', 'Executive', 'Technical'], required: true } }, classes: ['Professional', 'Executive', 'Technical'], rates: { Professional: 0.006, Executive: 0.008, Technical: 0.01 }, min_premium: 100000 },

  // ===== HEALTH INSURANCE =====
  { code: 'INDIVIDUAL_HEALTH', name: 'Individual Health Insurance', desc: 'Comprehensive health cover for individuals', category: 'HEALTH', icon: 'h', inputs: { age: { label: 'Age', type: 'number', required: true }, plan: { label: 'Plan', type: 'select', options: ['Bronze', 'Silver', 'Gold', 'Platinum'], required: true } }, classes: ['Bronze', 'Silver', 'Gold', 'Platinum'], rates: { Bronze: 0.03, Silver: 0.05, Gold: 0.08, Platinum: 0.12 }, min_premium: 50000 },
  { code: 'FAMILY_HEALTH', name: 'Family Health Plan', desc: 'Health cover for the whole family', category: 'HEALTH', icon: 'h', inputs: { adults: { label: 'Number of Adults', type: 'number', required: true }, children: { label: 'Number of Children', type: 'number', required: true }, plan: { label: 'Plan', type: 'select', options: ['Bronze', 'Silver', 'Gold', 'Platinum'], required: true } }, classes: ['Bronze', 'Silver', 'Gold', 'Platinum'], rates: { Bronze: 0.025, Silver: 0.04, Gold: 0.07, Platinum: 0.1 }, min_premium: 100000 },
  { code: 'CORPORATE_HMO', name: 'Corporate HMO', desc: 'Group health insurance for employees', category: 'HEALTH', icon: 'h', inputs: { employeeCount: { label: 'Number of Employees', type: 'number', required: true }, plan: { label: 'Plan', type: 'select', options: ['Bronze', 'Silver', 'Gold', 'Platinum'], required: true } }, classes: ['Bronze', 'Silver', 'Gold', 'Platinum'], rates: { Bronze: 0.02, Silver: 0.035, Gold: 0.06, Platinum: 0.09 }, min_premium: 200000 },
  { code: 'CRITICAL_ILLNESS', name: 'Critical Illness Cover', desc: 'Lump sum payment on diagnosis of covered critical illness', category: 'HEALTH', icon: 'h', inputs: { age: { label: 'Age', type: 'number', required: true }, sumInsured: { label: 'Sum Insured', type: 'number', required: true } }, classes: ['Standard'], rates: { Standard: 0.012 }, min_premium: 50000 },
  { code: 'HOSPITAL_CASH', name: 'Hospital Cash Plan', desc: 'Daily cash benefit for each day of hospitalisation', category: 'HEALTH', icon: 'h', inputs: { dailyBenefit: { label: 'Daily Benefit', type: 'select', options: [5000, 10000, 20000, 50000], required: true } }, classes: ['Standard'], rates: { Standard: 0.002 }, min_premium: 10000 },
  { code: 'CANCER_COVER', name: 'Cancer Cover', desc: 'Specific cover for cancer diagnosis and treatment', category: 'HEALTH', icon: 'h', inputs: { age: { label: 'Age', type: 'number', required: true }, sumAssured: { label: 'Sum Assured', type: 'number', required: true } }, classes: ['Standard'], rates: { Standard: 0.015 }, min_premium: 50000 },
  { code: 'INTL_MEDICAL', name: 'International Medical Insurance', desc: 'Global health cover for expatriates and frequent travellers', category: 'HEALTH', icon: 'h', inputs: { country: { label: 'Country/Region', type: 'select', options: ['Africa', 'Europe', 'Americas', 'Worldwide'], required: true }, age: { label: 'Age', type: 'number', required: true }, plan: { label: 'Plan', type: 'select', options: ['Essential', 'Standard', 'Premium'], required: true } }, classes: ['Essential', 'Standard', 'Premium'], rates: { Essential: 0.05, Standard: 0.08, Premium: 0.15 }, min_premium: 200000 },

  // ===== INCOME PROTECTION =====
  { code: 'INCOME_PROTECTION', name: 'Income Protection', desc: 'Replaces a portion of income if unable to work due to illness or injury', category: 'PERSONAL', icon: 'g', inputs: { monthlyIncome: { label: 'Monthly Income', type: 'number', required: true }, benefitPeriod: { label: 'Benefit Period (Months)', type: 'select', options: [12, 24, 60, 120], required: true } }, classes: ['Standard'], rates: { Standard: 0.008 }, min_premium: 25000 },
  { code: 'DISABILITY', name: 'Disability Insurance', desc: 'Monthly benefit if you become disabled and unable to work', category: 'PERSONAL', icon: 'g', inputs: { monthlyBenefit: { label: 'Monthly Benefit', type: 'number', required: true } }, classes: ['Standard'], rates: { Standard: 0.01 }, min_premium: 25000 },
  { code: 'PERM_DISABILITY', name: 'Permanent Disability Cover', desc: 'Lump sum on permanent total disability', category: 'PERSONAL', icon: 'g', inputs: { sumAssured: { label: 'Sum Assured', type: 'number', required: true } }, classes: ['Standard'], rates: { Standard: 0.006 }, min_premium: 30000 },
  { code: 'TEMP_DISABILITY', name: 'Temporary Disability Cover', desc: 'Weekly benefit during temporary disability', category: 'PERSONAL', icon: 'g', inputs: { weeklyBenefit: { label: 'Weekly Benefit', type: 'number', required: true } }, classes: ['Standard'], rates: { Standard: 0.004 }, min_premium: 10000 },
  { code: 'PERSONAL_ACCIDENT', name: 'Personal Accident Insurance', desc: 'Cover for accidental bodily injury or death', category: 'PERSONAL', icon: 'g', inputs: { sumInsured: { label: 'Sum Insured', type: 'number', required: true }, occupation: { label: 'Occupation', type: 'select', options: ['Low Risk', 'Medium Risk', 'High Risk'], required: true } }, classes: ['LowRisk', 'MediumRisk', 'HighRisk'], rates: { LowRisk: 0.003, MediumRisk: 0.005, HighRisk: 0.008 }, min_premium: 15000 },
  { code: 'ACCIDENTAL_DEATH', name: 'Accidental Death Cover', desc: 'Lump sum benefit on accidental death', category: 'PERSONAL', icon: 'g', inputs: { sumAssured: { label: 'Sum Assured', type: 'number', required: true } }, classes: ['Standard'], rates: { Standard: 0.002 }, min_premium: 10000 },

  // ===== SAVINGS & RETIREMENT =====
  { code: 'RETIREMENT', name: 'Retirement Plan', desc: 'Regular savings plan for retirement', category: 'PERSONAL', icon: 'g', inputs: { monthlyContribution: { label: 'Monthly Contribution', type: 'number', required: true } }, classes: ['Standard'], rates: { Standard: 0.0 }, min_premium: 10000 },
  { code: 'DEFERRED_ANNUITY', name: 'Deferred Annuity', desc: 'Annuity starting at a future retirement date', category: 'PERSONAL', icon: 'g', inputs: { retirementAge: { label: 'Retirement Age', type: 'number', required: true } }, classes: ['Standard'], rates: { Standard: 0.0 }, min_premium: 100000 },
  { code: 'IMMEDIATE_ANNUITY', name: 'Immediate Annuity', desc: 'Immediate income stream in exchange for lump sum', category: 'PERSONAL', icon: 'g', inputs: { purchasePrice: { label: 'Purchase Price', type: 'number', required: true } }, classes: ['Standard'], rates: { Standard: 0.0 }, min_premium: 500000 },
  { code: 'INVESTMENT_LINKED', name: 'Investment-linked Plan', desc: 'Life cover with investment component', category: 'LIFE', icon: 'g', inputs: { contribution: { label: 'Monthly Contribution', type: 'number', required: true } }, classes: ['Standard'], rates: { Standard: 0.0 }, min_premium: 25000 },

  // ===== PERSONAL PROPERTY =====
  { code: 'HOMEOWNERS', name: 'Homeowners Insurance', desc: 'Cover for building and contents against specified perils', category: 'PERSONAL', icon: 'o', inputs: { buildingValue: { label: 'Building Value', type: 'number', required: true }, contentsValue: { label: 'Contents Value', type: 'number', required: true } }, classes: ['Urban', 'Suburban', 'Rural'], rates: { Urban: 0.002, Suburban: 0.0025, Rural: 0.003 }, min_premium: 50000 },
  { code: 'TENANTS', name: 'Tenants Insurance', desc: 'Cover for tenants contents and personal belongings', category: 'PERSONAL', icon: 'o', inputs: { contentsValue: { label: 'Contents Value', type: 'number', required: true } }, classes: ['Standard'], rates: { Standard: 0.003 }, min_premium: 25000 },
  { code: 'HOUSEHOLD_CONTENTS', name: 'Household Contents', desc: 'Cover for household items against theft, fire, and damage', category: 'PERSONAL', icon: 'o', inputs: { sumInsured: { label: 'Sum Insured', type: 'number', required: true } }, classes: ['Standard'], rates: { Standard: 0.004 }, min_premium: 20000 },
  { code: 'GADGET', name: 'Gadget Insurance', desc: 'Cover for electronic gadgets against accidental damage and theft', category: 'PERSONAL', icon: 'o', inputs: { deviceValue: { label: 'Device Value', type: 'number', required: true } }, classes: ['Standard'], rates: { Standard: 0.05 }, min_premium: 5000 },
  { code: 'MOBILE_PHONE', name: 'Mobile Phone Insurance', desc: 'Cover for mobile phones against damage, loss, and theft', category: 'PERSONAL', icon: 'o', inputs: { deviceValue: { label: 'Device Value', type: 'number', required: true } }, classes: ['Standard'], rates: { Standard: 0.08 }, min_premium: 3000 },
  { code: 'LAPTOP', name: 'Laptop Insurance', desc: 'Cover for laptops against accidental damage and theft', category: 'PERSONAL', icon: 'o', inputs: { deviceValue: { label: 'Device Value', type: 'number', required: true } }, classes: ['Standard'], rates: { Standard: 0.06 }, min_premium: 5000 },
  { code: 'JEWELLERY', name: 'Jewellery Insurance', desc: 'Cover for valuable jewellery against loss, theft, and damage', category: 'PERSONAL', icon: 'o', inputs: { declaredValue: { label: 'Declared Value', type: 'number', required: true } }, classes: ['Standard'], rates: { Standard: 0.015 }, min_premium: 10000 },
  { code: 'FINE_ARTS', name: 'Fine Arts Insurance', desc: 'Cover for fine art and collectibles against damage and theft', category: 'PERSONAL', icon: 'o', inputs: { declaredValue: { label: 'Declared Value', type: 'number', required: true } }, classes: ['Standard'], rates: { Standard: 0.012 }, min_premium: 25000 },

  // ===== PERSONAL MOBILITY =====
  { code: 'MOTOR_TP', name: 'Motor Third Party', desc: 'Third-party liability cover for vehicles (statutory minimum)', category: 'PERSONAL', icon: 'g', inputs: { vehicleValue: { label: 'Vehicle Value', type: 'number', required: true } }, classes: ['Private', 'Commercial'], rates: { Private: 0.015, Commercial: 0.02 }, min_premium: 75000 },
  { code: 'MOTORCYCLE', name: 'Motorcycle Insurance', desc: 'Cover for motorcycles against damage and third-party liability', category: 'PERSONAL', icon: 'g', inputs: { vehicleValue: { label: 'Motorcycle Value', type: 'number', required: true } }, classes: ['Standard'], rates: { Standard: 0.04 }, min_premium: 15000 },
  { code: 'EV_INSURANCE', name: 'Electric Vehicle Insurance', desc: 'Specialised cover for electric vehicles', category: 'PERSONAL', icon: 'g', inputs: { vehicleValue: { label: 'Vehicle Value', type: 'number', required: true } }, classes: ['Standard'], rates: { Standard: 0.045 }, min_premium: 100000 },
  { code: 'TRAVEL', name: 'Travel Insurance', desc: 'Cover for trip cancellation, medical expenses, and baggage loss', category: 'PERSONAL', icon: 'g', inputs: { destination: { label: 'Destination', type: 'select', options: ['Domestic', 'Africa', 'Europe', 'Americas', 'Asia', 'Worldwide'], required: true }, duration: { label: 'Duration (Days)', type: 'number', required: true } }, classes: ['Domestic', 'Africa', 'Europe', 'Americas', 'Asia', 'Worldwide'], rates: { Domestic: 0.002, Africa: 0.004, Europe: 0.005, Americas: 0.006, Asia: 0.005, Worldwide: 0.008 }, min_premium: 5000 },
  { code: 'BICYCLE', name: 'Bicycle Insurance', desc: 'Cover for bicycles against theft and accidental damage', category: 'PERSONAL', icon: 'g', inputs: { bicycleValue: { label: 'Bicycle Value', type: 'number', required: true } }, classes: ['Standard'], rates: { Standard: 0.06 }, min_premium: 5000 },

  // ===== B. COMMERCIAL - PROPERTY =====
  { code: 'INDUSTRIAL_ALL_RISKS', name: 'Industrial All Risks', desc: 'Comprehensive cover for all physical assets of industrial operations', category: 'BUSINESS', icon: 'o', inputs: { assetValue: { label: 'Total Asset Value', type: 'number', required: true } }, classes: ['Light', 'Heavy', 'Chemical'], rates: { Light: 0.005, Heavy: 0.008, Chemical: 0.012 }, min_premium: 200000 },
  { code: 'BURGLARY', name: 'Burglary Insurance', desc: 'Cover for loss of contents due to burglary, theft, or attempted theft', category: 'BUSINESS', icon: 'o', inputs: { contentsValue: { label: 'Contents Value', type: 'number', required: true } }, classes: ['Standard', 'HighRisk'], rates: { Standard: 0.005, HighRisk: 0.01 }, min_premium: 50000 },
  { code: 'MONEY', name: 'Money Insurance', desc: 'Cover for cash and money in transit and on premises', category: 'BUSINESS', icon: 'o', inputs: { cashLimit: { label: 'Cash Limit', type: 'number', required: true } }, classes: ['Standard'], rates: { Standard: 0.008 }, min_premium: 25000 },
  { code: 'ALL_RISKS', name: 'All Risks Insurance', desc: 'Comprehensive cover for movable property and equipment', category: 'BUSINESS', icon: 'o', inputs: { sumInsured: { label: 'Sum Insured', type: 'number', required: true } }, classes: ['Standard'], rates: { Standard: 0.007 }, min_premium: 50000 },
  { code: 'BI', name: 'Business Interruption', desc: 'Cover for loss of income following a property damage event', category: 'BUSINESS', icon: 'o', inputs: { grossProfit: { label: 'Estimated Gross Profit', type: 'number', required: true } }, classes: ['Standard'], rates: { Standard: 0.004 }, min_premium: 100000 },
  { code: 'STOCK_DETERIORATION', name: 'Deterioration of Stock', desc: 'Cover for deterioration or spoilage of stored goods', category: 'BUSINESS', icon: 'o', inputs: { stockValue: { label: 'Stock Value', type: 'number', required: true } }, classes: ['Standard'], rates: { Standard: 0.005 }, min_premium: 50000 },
  { code: 'PLATE_GLASS', name: 'Plate Glass Insurance', desc: 'Cover for breakage of glass, windows, and glass fixtures', category: 'BUSINESS', icon: 'o', inputs: { replacementCost: { label: 'Replacement Cost', type: 'number', required: true } }, classes: ['Standard'], rates: { Standard: 0.03 }, min_premium: 10000 },
  { code: 'NEON_SIGN', name: 'Neon Sign Insurance', desc: 'Cover for damage to signage and outdoor displays', category: 'BUSINESS', icon: 'o', inputs: { replacementCost: { label: 'Replacement Cost', type: 'number', required: true } }, classes: ['Standard'], rates: { Standard: 0.04 }, min_premium: 15000 },

  // ===== COMMERCIAL - LIABILITY =====
  { code: 'PRODUCTS_LIABILITY', name: 'Products Liability', desc: 'Cover for liability arising from products sold or manufactured', category: 'BUSINESS', icon: 'b', inputs: { turnover: { label: 'Annual Turnover', type: 'number', required: true } }, classes: ['LowRisk', 'MediumRisk', 'HighRisk'], rates: { LowRisk: 0.002, MediumRisk: 0.004, HighRisk: 0.007 }, min_premium: 50000 },
  { code: 'EMPLOYERS_LIABILITY', name: 'Employers Liability', desc: 'Cover for liability to employees for injury or disease', category: 'BUSINESS', icon: 'b', inputs: { payroll: { label: 'Annual Payroll', type: 'number', required: true } }, classes: ['Standard'], rates: { Standard: 0.003 }, min_premium: 50000 },
  { code: 'OCCUPIERS_LIABILITY', name: 'Occupiers Liability', desc: 'Cover for liability to persons on the insured premises', category: 'BUSINESS', icon: 'b', inputs: { buildingSize: { label: 'Building Size (sqm)', type: 'number', required: true }, riskLevel: { label: 'Risk Level', type: 'select', options: ['Low', 'Medium', 'High'], required: true } }, classes: ['Low', 'Medium', 'High'], rates: { Low: 0.002, Medium: 0.004, High: 0.007 }, min_premium: 50000 },
  { code: 'PROF_INDEMNITY', name: 'Professional Indemnity', desc: 'Cover for liability from professional errors, omissions, or negligence', category: 'BUSINESS', icon: 'b', inputs: { fees: { label: 'Annual Fees/Turnover', type: 'number', required: true } }, classes: ['LowRisk', 'MediumRisk', 'HighRisk'], rates: { LowRisk: 0.005, MediumRisk: 0.01, HighRisk: 0.02 }, min_premium: 100000 },
  { code: 'D_O', name: 'Directors & Officers Liability', desc: 'Cover for directors and officers against claims for wrongful acts', category: 'BUSINESS', icon: 'b', inputs: { companySize: { label: 'Company Revenue', type: 'number', required: true } }, classes: ['Small', 'Medium', 'Large'], rates: { Small: 0.008, Medium: 0.012, Large: 0.018 }, min_premium: 200000 },
  { code: 'CYBER_LIABILITY', name: 'Cyber Liability', desc: 'Cover for data breaches, cyber attacks, and privacy violations', category: 'BUSINESS', icon: 'b', inputs: { revenue: { label: 'Annual Revenue', type: 'number', required: true }, dataType: { label: 'Data Type', type: 'select', options: ['Basic', 'Financial', 'Health', 'All'], required: true } }, classes: ['Basic', 'Financial', 'Health', 'All'], rates: { Basic: 0.003, Financial: 0.005, Health: 0.007, All: 0.01 }, min_premium: 100000 },
  { code: 'EMP_PRACTICES', name: 'Employment Practices Liability', desc: 'Cover for claims from employees for discrimination, harassment, etc.', category: 'BUSINESS', icon: 'b', inputs: { employees: { label: 'Number of Employees', type: 'number', required: true } }, classes: ['Standard'], rates: { Standard: 0.004 }, min_premium: 75000 },
  { code: 'MED_MALPRACTICE', name: 'Medical Malpractice', desc: 'Cover for healthcare professionals against negligence claims', category: 'BUSINESS', icon: 'b', inputs: { beds: { label: 'Number of Beds', type: 'number', required: true }, revenue: { label: 'Annual Revenue', type: 'number', required: true } }, classes: ['Clinic', 'Hospital', 'Specialist'], rates: { Clinic: 0.015, Hospital: 0.01, Specialist: 0.02 }, min_premium: 150000 },
  { code: 'E_AND_O', name: 'Errors & Omissions', desc: 'Cover for professional services firms against client claims', category: 'BUSINESS', icon: 'b', inputs: { turnover: { label: 'Annual Turnover', type: 'number', required: true } }, classes: ['LowRisk', 'MediumRisk', 'HighRisk'], rates: { LowRisk: 0.005, MediumRisk: 0.01, HighRisk: 0.018 }, min_premium: 100000 },

  // ===== EMPLOYEE BENEFITS =====
  { code: 'GROUP_LIFE', name: 'Group Life Insurance', desc: 'Life cover for a group of employees at competitive rates', category: 'BUSINESS', icon: 'g', inputs: { salaryRoll: { label: 'Total Annual Salary Roll', type: 'number', required: true }, employeeCount: { label: 'Number of Employees', type: 'number', required: true } }, classes: ['Standard'], rates: { Standard: 0.005 }, min_premium: 50000 },
  { code: 'GROUP_HEALTH', name: 'Group Health Insurance', desc: 'Health insurance cover for employee groups', category: 'BUSINESS', icon: 'h', inputs: { employeeCount: { label: 'Number of Employees', type: 'number', required: true }, plan: { label: 'Plan', type: 'select', options: ['Basic', 'Standard', 'Premium'], required: true } }, classes: ['Basic', 'Standard', 'Premium'], rates: { Basic: 0.02, Standard: 0.04, Premium: 0.07 }, min_premium: 150000 },
  { code: 'WORKMEN_COMP', name: 'Workmen Compensation', desc: 'Statutory compensation cover for workplace injuries', category: 'BUSINESS', icon: 'g', inputs: { payroll: { label: 'Annual Payroll', type: 'number', required: true } }, classes: ['LowRisk', 'MediumRisk', 'HighRisk'], rates: { LowRisk: 0.002, MediumRisk: 0.004, HighRisk: 0.008 }, min_premium: 25000 },
  { code: 'KEYMAN', name: 'Keyman Insurance', desc: 'Life and disability cover on key employees whose loss would impact business', category: 'BUSINESS', icon: 'g', inputs: { sumAssured: { label: 'Sum Assured', type: 'number', required: true } }, classes: ['Standard'], rates: { Standard: 0.008 }, min_premium: 100000 },

  // ===== COMMERCIAL MOTOR =====
  { code: 'FLEET', name: 'Fleet Insurance', desc: 'Comprehensive cover for a fleet of vehicles', category: 'BUSINESS', icon: 'g', inputs: { fleetValue: { label: 'Total Fleet Value', type: 'number', required: true }, vehicleCount: { label: 'Number of Vehicles', type: 'number', required: true } }, classes: ['Small', 'Medium', 'Large'], rates: { Small: 0.048, Medium: 0.045, Large: 0.04 }, min_premium: 250000 },
  { code: 'COMMERCIAL_MOTOR', name: 'Commercial Motor', desc: 'Cover for commercial vehicles used for business purposes', category: 'BUSINESS', icon: 'g', inputs: { vehicleValue: { label: 'Vehicle Value', type: 'number', required: true } }, classes: ['Light', 'Medium', 'Heavy'], rates: { Light: 0.045, Medium: 0.05, Heavy: 0.055 }, min_premium: 100000 },
  { code: 'HAULAGE', name: 'Haulage Insurance', desc: 'Cover for haulage trucks and long-distance transport vehicles', category: 'BUSINESS', icon: 'g', inputs: { vehicleValue: { label: 'Vehicle Value', type: 'number', required: true } }, classes: ['Standard'], rates: { Standard: 0.065 }, min_premium: 150000 },
  { code: 'SCHOOL_BUS', name: 'School Bus Insurance', desc: 'Cover for school buses with enhanced passenger liability', category: 'BUSINESS', icon: 'g', inputs: { vehicleValue: { label: 'Vehicle Value', type: 'number', required: true } }, classes: ['Standard'], rates: { Standard: 0.045 }, min_premium: 100000 },
  { code: 'AMBULANCE', name: 'Ambulance Insurance', desc: 'Cover for ambulance vehicles including medical equipment', category: 'BUSINESS', icon: 'g', inputs: { vehicleValue: { label: 'Vehicle Value', type: 'number', required: true } }, classes: ['Standard'], rates: { Standard: 0.04 }, min_premium: 120000 },
  { code: 'AGRI_VEHICLE', name: 'Agricultural Vehicle Insurance', desc: 'Cover for farm vehicles and agricultural machinery', category: 'BUSINESS', icon: 'g', inputs: { vehicleValue: { label: 'Vehicle Value', type: 'number', required: true } }, classes: ['Standard'], rates: { Standard: 0.035 }, min_premium: 75000 },

  // ===== C. ENGINEERING =====
  { code: 'CAR', name: 'Contractors All Risks', desc: 'Cover for contractors against physical loss or damage during construction', category: 'ENGINEERING', icon: 'o', inputs: { contractValue: { label: 'Contract Value', type: 'number', required: true } }, classes: ['Building', 'Civil', 'Industrial'], rates: { Building: 0.006, Civil: 0.008, Industrial: 0.01 }, min_premium: 150000 },
  { code: 'EAR', name: 'Erection All Risks', desc: 'Cover for erection and installation projects', category: 'ENGINEERING', icon: 'o', inputs: { projectValue: { label: 'Project Value', type: 'number', required: true } }, classes: ['Standard'], rates: { Standard: 0.007 }, min_premium: 150000 },
  { code: 'CPM', name: 'Contractors Plant & Machinery', desc: 'Cover for contractors plant and construction equipment', category: 'ENGINEERING', icon: 'o', inputs: { equipmentValue: { label: 'Equipment Value', type: 'number', required: true } }, classes: ['Standard'], rates: { Standard: 0.008 }, min_premium: 100000 },
  { code: 'MB', name: 'Machinery Breakdown', desc: 'Cover for sudden and unforeseen breakdown of machinery', category: 'ENGINEERING', icon: 'o', inputs: { replacementValue: { label: 'Replacement Value', type: 'number', required: true } }, classes: ['Light', 'Medium', 'Heavy'], rates: { Light: 0.005, Medium: 0.008, Heavy: 0.012 }, min_premium: 100000 },
  { code: 'EE', name: 'Electronic Equipment', desc: 'Cover for electronic equipment against all risks', category: 'ENGINEERING', icon: 'o', inputs: { equipmentValue: { label: 'Equipment Value', type: 'number', required: true } }, classes: ['Office', 'Medical', 'Industrial'], rates: { Office: 0.004, Medical: 0.006, Industrial: 0.008 }, min_premium: 50000 },
  { code: 'BOILER', name: 'Boiler & Pressure Plant', desc: 'Cover for boilers, pressure vessels, and related plant', category: 'ENGINEERING', icon: 'o', inputs: { replacementValue: { label: 'Replacement Value', type: 'number', required: true } }, classes: ['Standard'], rates: { Standard: 0.01 }, min_premium: 100000 },
  { code: 'MLOP', name: 'Machinery Loss of Profits', desc: 'Cover for loss of profit following machinery breakdown', category: 'ENGINEERING', icon: 'o', inputs: { grossProfit: { label: 'Estimated Gross Profit', type: 'number', required: true } }, classes: ['Standard'], rates: { Standard: 0.006 }, min_premium: 150000 },

  // ===== D. MARINE =====
  { code: 'MARINE_CARGO', name: 'Marine Cargo', desc: 'Cover for cargo in transit by sea', category: 'MARINE', icon: 'o', inputs: { cargoValue: { label: 'Cargo Value', type: 'number', required: true } }, classes: ['General', 'Refrigerated', 'Bulk', 'Container'], rates: { General: 0.003, Refrigerated: 0.004, Bulk: 0.0025, Container: 0.002 }, min_premium: 50000 },
  { code: 'MARINE_HULL', name: 'Marine Hull', desc: 'Cover for the vessel itself against marine perils', category: 'MARINE', icon: 'o', inputs: { vesselValue: { label: 'Vessel Value', type: 'number', required: true } }, classes: ['Fishing', 'Cargo', 'Passenger', 'Tanker'], rates: { Fishing: 0.015, Cargo: 0.012, Passenger: 0.01, Tanker: 0.02 }, min_premium: 200000 },
  { code: 'INLAND_TRANSIT', name: 'Inland Transit', desc: 'Cover for goods in transit by road, rail, or inland waterways', category: 'MARINE', icon: 'o', inputs: { goodsValue: { label: 'Goods Value', type: 'number', required: true } }, classes: ['Standard'], rates: { Standard: 0.003 }, min_premium: 25000 },
  { code: 'GOODS_IN_TRANSIT', name: 'Goods in Transit', desc: 'Cover for merchandise while being transported', category: 'MARINE', icon: 'o', inputs: { cargoValue: { label: 'Cargo Value', type: 'number', required: true } }, classes: ['Standard'], rates: { Standard: 0.004 }, min_premium: 25000 },
  { code: 'FREIGHT', name: 'Freight Insurance', desc: 'Cover for freight charges in the event of loss', category: 'MARINE', icon: 'o', inputs: { freightCharges: { label: 'Freight Charges', type: 'number', required: true } }, classes: ['Standard'], rates: { Standard: 0.002 }, min_premium: 15000 },
  { code: 'STOCK_THROUGHPUT', name: 'Stock Throughput', desc: 'Cover for stock throughout the supply chain', category: 'MARINE', icon: 'o', inputs: { annualTurnover: { label: 'Annual Turnover', type: 'number', required: true } }, classes: ['Standard'], rates: { Standard: 0.0025 }, min_premium: 100000 },

  // ===== E. AVIATION =====
  { code: 'AIRCRAFT_HULL', name: 'Aircraft Hull', desc: 'Cover for damage to or loss of aircraft', category: 'AVIATION', icon: 'g', inputs: { aircraftValue: { label: 'Aircraft Value', type: 'number', required: true } }, classes: ['Private', 'Commercial', 'Cargo'], rates: { Private: 0.02, Commercial: 0.015, Cargo: 0.018 }, min_premium: 500000 },
  { code: 'PASSENGER_LIABILITY', name: 'Passenger Liability', desc: 'Cover for liability to passengers on aircraft', category: 'AVIATION', icon: 'b', inputs: { passengerCapacity: { label: 'Passenger Capacity', type: 'number', required: true } }, classes: ['Standard'], rates: { Standard: 0.005 }, min_premium: 200000 },
  { code: 'AIRPORT_LIABILITY', name: 'Airport Liability', desc: 'Cover for airport operators liability', category: 'AVIATION', icon: 'b', inputs: { revenue: { label: 'Annual Revenue', type: 'number', required: true } }, classes: ['Small', 'Medium', 'Large'], rates: { Small: 0.004, Medium: 0.006, Large: 0.008 }, min_premium: 300000 },

  // ===== F. OIL & GAS / ENERGY =====
  { code: 'CONTROL_OF_WELL', name: 'Control of Well', desc: 'Cover for well control and re-drilling costs', category: 'ENERGY', icon: 'o', inputs: { contractValue: { label: 'Contract Value', type: 'number', required: true } }, classes: ['Standard'], rates: { Standard: 0.02 }, min_premium: 1000000 },
  { code: 'OFFSHORE_ENERGY', name: 'Offshore Energy', desc: 'Cover for offshore energy installations and operations', category: 'ENERGY', icon: 'o', inputs: { assetValue: { label: 'Asset Value', type: 'number', required: true } }, classes: ['Standard'], rates: { Standard: 0.015 }, min_premium: 2000000 },
  { code: 'ONSHORE_ENERGY', name: 'Onshore Energy', desc: 'Cover for onshore energy facilities and operations', category: 'ENERGY', icon: 'o', inputs: { assetValue: { label: 'Asset Value', type: 'number', required: true } }, classes: ['Standard'], rates: { Standard: 0.01 }, min_premium: 1000000 },
  { code: 'PIPELINE', name: 'Pipeline Insurance', desc: 'Cover for pipelines against damage and business interruption', category: 'ENERGY', icon: 'o', inputs: { pipelineValue: { label: 'Pipeline Value', type: 'number', required: true } }, classes: ['Standard'], rates: { Standard: 0.008 }, min_premium: 500000 },

  // ===== G. AGRICULTURE =====
  { code: 'CROP', name: 'Crop Insurance', desc: 'Cover for crops against adverse weather, pests, and disease', category: 'AGRICULTURE', icon: 'o', inputs: { farmSize: { label: 'Farm Size (Hectares)', type: 'number', required: true }, cropType: { label: 'Crop Type', type: 'select', options: ['Maize', 'Rice', 'Cassava', 'Vegetables', 'Mixed'], required: true } }, classes: ['Maize', 'Rice', 'Cassava', 'Vegetables', 'Mixed'], rates: { Maize: 0.04, Rice: 0.05, Cassava: 0.035, Vegetables: 0.06, Mixed: 0.045 }, min_premium: 25000 },
  { code: 'POULTRY', name: 'Poultry Insurance', desc: 'Cover for poultry birds against disease and mortality', category: 'AGRICULTURE', icon: 'o', inputs: { birdValue: { label: 'Total Bird Value', type: 'number', required: true } }, classes: ['Broilers', 'Layers', 'Breeders'], rates: { Broilers: 0.05, Layers: 0.045, Breeders: 0.04 }, min_premium: 20000 },
  { code: 'LIVESTOCK', name: 'Livestock Insurance', desc: 'Cover for cattle, sheep, goats, and other livestock', category: 'AGRICULTURE', icon: 'o', inputs: { animalValue: { label: 'Total Animal Value', type: 'number', required: true } }, classes: ['Cattle', 'Sheep', 'Goats', 'Mixed'], rates: { Cattle: 0.035, Sheep: 0.04, Goats: 0.045, Mixed: 0.04 }, min_premium: 25000 },
  { code: 'FISH_FARM', name: 'Fish Farm Insurance', desc: 'Cover for fish farms against mortality and water quality issues', category: 'AGRICULTURE', icon: 'o', inputs: { stockValue: { label: 'Fish Stock Value', type: 'number', required: true } }, classes: ['Standard'], rates: { Standard: 0.05 }, min_premium: 30000 },
  { code: 'GREENHOUSE', name: 'Greenhouse Insurance', desc: 'Cover for greenhouse structures and crops inside', category: 'AGRICULTURE', icon: 'o', inputs: { structureValue: { label: 'Structure Value', type: 'number', required: true } }, classes: ['Standard'], rates: { Standard: 0.025 }, min_premium: 50000 },

  // ===== H. CONSTRUCTION & REAL ESTATE =====
  { code: 'BUILDERS_RISK', name: 'Builders Risk', desc: 'Cover for buildings under construction', category: 'CONSTRUCTION', icon: 'o', inputs: { contractValue: { label: 'Contract Value', type: 'number', required: true } }, classes: ['Residential', 'Commercial', 'Industrial'], rates: { Residential: 0.005, Commercial: 0.006, Industrial: 0.008 }, min_premium: 100000 },
  { code: 'BUILDING', name: 'Building Insurance', desc: 'Cover for completed buildings against specified perils', category: 'CONSTRUCTION', icon: 'o', inputs: { reinstatementValue: { label: 'Reinstatement Value', type: 'number', required: true } }, classes: ['Residential', 'Commercial', 'Industrial'], rates: { Residential: 0.002, Commercial: 0.0025, Industrial: 0.0035 }, min_premium: 75000 },
  { code: 'DEVELOPERS_LIABILITY', name: 'Developers Liability', desc: 'Cover for property developers against construction-related claims', category: 'CONSTRUCTION', icon: 'b', inputs: { contractValue: { label: 'Contract Value', type: 'number', required: true } }, classes: ['Standard'], rates: { Standard: 0.004 }, min_premium: 150000 },
  { code: 'LATENT_DEFECTS', name: 'Latent Defects Insurance', desc: 'Cover for hidden structural defects in buildings after completion', category: 'CONSTRUCTION', icon: 'o', inputs: { projectValue: { label: 'Project Value', type: 'number', required: true } }, classes: ['Standard'], rates: { Standard: 0.015 }, min_premium: 250000 },

  // ===== I. FINANCIAL RISKS =====
  { code: 'BANKERS_BLANKET', name: 'Bankers Blanket Bond', desc: 'Cover for banks against employee dishonesty and theft', category: 'FINANCIAL', icon: 'o', inputs: { limit: { label: 'Limit of Indemnity', type: 'number', required: true } }, classes: ['Standard'], rates: { Standard: 0.008 }, min_premium: 500000 },
  { code: 'CASH_IN_TRANSIT', name: 'Cash in Transit', desc: 'Cover for cash and valuables during transportation', category: 'FINANCIAL', icon: 'o', inputs: { cashLimit: { label: 'Cash Limit per Trip', type: 'number', required: true } }, classes: ['Standard'], rates: { Standard: 0.006 }, min_premium: 50000 },
  { code: 'COMPUTER_FRAUD', name: 'Computer Fraud', desc: 'Cover for financial loss due to computer crime and fraud', category: 'FINANCIAL', icon: 'o', inputs: { revenue: { label: 'Annual Revenue', type: 'number', required: true } }, classes: ['Standard'], rates: { Standard: 0.003 }, min_premium: 100000 },
  { code: 'CRIME', name: 'Crime Insurance', desc: 'Cover for various crime risks including theft, fraud, and forgery', category: 'FINANCIAL', icon: 'o', inputs: { revenue: { label: 'Annual Revenue', type: 'number', required: true } }, classes: ['Standard'], rates: { Standard: 0.0025 }, min_premium: 100000 },
  { code: 'TRADE_CREDIT', name: 'Trade Credit Insurance', desc: 'Cover for non-payment by trade debtors', category: 'FINANCIAL', icon: 'o', inputs: { turnover: { label: 'Annual Turnover', type: 'number', required: true } }, classes: ['Standard'], rates: { Standard: 0.005 }, min_premium: 200000 },
  { code: 'POLITICAL_VIOLENCE', name: 'Political Violence', desc: 'Cover for damage from terrorism, riot, strike, and political unrest', category: 'FINANCIAL', icon: 'o', inputs: { assetValue: { label: 'Asset Value', type: 'number', required: true } }, classes: ['LowRisk', 'MediumRisk', 'HighRisk'], rates: { LowRisk: 0.003, MediumRisk: 0.006, HighRisk: 0.012 }, min_premium: 100000 },

  // ===== J. SURETY & BONDS =====
  { code: 'BID_BOND', name: 'Bid Bond', desc: 'Guarantee that a contractor will honour a bid if selected', category: 'SURETY', icon: 'o', inputs: { bondAmount: { label: 'Bond Amount', type: 'number', required: true } }, classes: ['Standard'], rates: { Standard: 0.015 }, min_premium: 25000 },
  { code: 'PERFORMANCE_BOND', name: 'Performance Bond', desc: 'Guarantee of contract performance by the contractor', category: 'SURETY', icon: 'o', inputs: { contractValue: { label: 'Contract Value', type: 'number', required: true } }, classes: ['Standard'], rates: { Standard: 0.02 }, min_premium: 50000 },
  { code: 'ADVANCE_PAYMENT_BOND', name: 'Advance Payment Bond', desc: 'Guarantee for advanced payments made to a contractor', category: 'SURETY', icon: 'o', inputs: { advanceAmount: { label: 'Advance Amount', type: 'number', required: true } }, classes: ['Standard'], rates: { Standard: 0.018 }, min_premium: 50000 },
  { code: 'CUSTOMS_BOND', name: 'Customs Bond', desc: 'Guarantee for customs duties and taxes', category: 'SURETY', icon: 'o', inputs: { bondValue: { label: 'Bond Value', type: 'number', required: true } }, classes: ['Standard'], rates: { Standard: 0.012 }, min_premium: 25000 },
  { code: 'JUDICIAL_BOND', name: 'Judicial Bond', desc: 'Guarantee required by courts for legal proceedings', category: 'SURETY', icon: 'o', inputs: { bondAmount: { label: 'Bond Amount', type: 'number', required: true } }, classes: ['Standard'], rates: { Standard: 0.01 }, min_premium: 25000 },

  // ===== K. SPECIALTY RISKS =====
  { code: 'EVENT', name: 'Event Insurance', desc: 'Cover for event cancellation, postponement, or abandonment', category: 'SPECIALTY', icon: 'o', inputs: { eventBudget: { label: 'Event Budget', type: 'number', required: true } }, classes: ['Standard'], rates: { Standard: 0.008 }, min_premium: 25000 },
  { code: 'WEDDING', name: 'Wedding Insurance', desc: 'Cover for wedding cancellation, vendor failure, and related risks', category: 'SPECIALTY', icon: 'o', inputs: { eventValue: { label: 'Event Value', type: 'number', required: true } }, classes: ['Standard'], rates: { Standard: 0.01 }, min_premium: 15000 },
  { code: 'EXHIBITION', name: 'Exhibition Insurance', desc: 'Cover for exhibition stands, displays, and exhibits', category: 'SPECIALTY', icon: 'o', inputs: { assetValue: { label: 'Exhibit Value', type: 'number', required: true } }, classes: ['Standard'], rates: { Standard: 0.006 }, min_premium: 25000 },
  { code: 'FILM_PRODUCTION', name: 'Film Production Insurance', desc: 'Cover for film and video production risks', category: 'SPECIALTY', icon: 'o', inputs: { productionBudget: { label: 'Production Budget', type: 'number', required: true } }, classes: ['Standard'], rates: { Standard: 0.01 }, min_premium: 100000 },
  { code: 'SPORTS', name: 'Sports Insurance', desc: 'Cover for sports events, teams, and participants', category: 'SPECIALTY', icon: 'o', inputs: { participants: { label: 'Number of Participants', type: 'number', required: true }, sportType: { label: 'Sport Type', type: 'select', options: ['Low Risk', 'Medium Risk', 'High Risk'], required: true } }, classes: ['LowRisk', 'MediumRisk', 'HighRisk'], rates: { LowRisk: 0.003, MediumRisk: 0.006, HighRisk: 0.012 }, min_premium: 25000 },
  { code: 'DRONE', name: 'Drone Insurance', desc: 'Cover for drones against damage, loss, and liability', category: 'SPECIALTY', icon: 'g', inputs: { droneValue: { label: 'Drone Value', type: 'number', required: true } }, classes: ['Recreational', 'Commercial'], rates: { Recreational: 0.05, Commercial: 0.08 }, min_premium: 15000 },
  { code: 'CYBER_CRIME', name: 'Cyber Crime Insurance', desc: 'Cover for financial loss from cyber crime activities', category: 'SPECIALTY', icon: 'o', inputs: { revenue: { label: 'Annual Revenue', type: 'number', required: true } }, classes: ['Standard'], rates: { Standard: 0.004 }, min_premium: 150000 },
  { code: 'TERRORISM', name: 'Terrorism Insurance', desc: 'Cover for damage and loss from terrorist acts', category: 'SPECIALTY', icon: 'o', inputs: { assetValue: { label: 'Asset Value', type: 'number', required: true } }, classes: ['Standard'], rates: { Standard: 0.005 }, min_premium: 200000 },
  { code: 'KIDNAP', name: 'Kidnap & Ransom', desc: 'Cover for kidnap, ransom, extortion, and crisis management costs', category: 'SPECIALTY', icon: 'o', inputs: { limit: { label: 'Limit of Indemnity', type: 'number', required: true } }, classes: ['Standard'], rates: { Standard: 0.025 }, min_premium: 300000 },
  { code: 'ENVIRONMENTAL', name: 'Environmental Liability', desc: 'Cover for environmental damage and clean-up costs', category: 'SPECIALTY', icon: 'o', inputs: { turnover: { label: 'Annual Turnover', type: 'number', required: true } }, classes: ['LowRisk', 'MediumRisk', 'HighRisk'], rates: { LowRisk: 0.003, MediumRisk: 0.006, HighRisk: 0.012 }, min_premium: 200000 },
];

module.exports = { catalog };
